// netlify/functions/calendar-feed.js
//
// Generates an ICS (iCalendar) subscription feed for a member, covering:
//   - Deals with a closing_date set (skips Closed/Dead stages)
//   - Stale deals (30+ days no activity, same rule the CRM already uses)
//   - Known upcoming FORGE/partner webinars (hardcoded until an events
//     table exists)
//
// This endpoint is NOT protected by Memberstack auth — calendar apps
// (Google/Outlook/Apple) fetch subscription feeds with a plain GET and
// cannot send a custom Authorization header. Instead, each member has a
// long random token (member_profiles.calendar_feed_token, generated by
// profile-data.js) embedded directly in their personal feed URL. Treat
// this token as a bearer credential: anyone with the URL can read that
// member's deal titles/dates, so it must never be logged or exposed
// outside the member's own profile page.
//
// Route:
//   GET ?token=<calendar_feed_token>  -> text/calendar ICS feed

const { supabase } = require('./_Lib/supabase-client');
const { json } = require('./_Lib/http');

const STALE_DAYS = 30; // must match crm-deals.js

// Known webinar dates. Move to a real table once partner events need to be
// added dynamically rather than by editing this file.
const WEBINARS = [
  {
    uid: 'forge-webinar-2026-09-09',
    title: 'FORGE Webinar',
    // Sept 9, 2026, 7:00 PM ET = 23:00 UTC (EDT, UTC-4, in effect in September)
    startUtc: '20260909T230000Z',
    endUtc: '20260910T010000Z',
  },
];

function icsEscape(str) {
  return String(str).replace(/\\/g, '\\\\').replace(/;/g, '\\;').replace(/,/g, '\\,').replace(/\n/g, '\\n');
}

function formatDateOnly(dateStr) {
  // 'YYYY-MM-DD' -> 'YYYYMMDD'
  return dateStr.replace(/-/g, '');
}

function addOneDay(dateStr) {
  const d = new Date(dateStr + 'T00:00:00Z');
  d.setUTCDate(d.getUTCDate() + 1);
  return d.toISOString().slice(0, 10);
}

function nowStamp() {
  return new Date().toISOString().replace(/[-:]/g, '').split('.')[0] + 'Z';
}

exports.handler = async function (event, context) {
  if (event.httpMethod !== 'GET') return json(405, { error: 'Method not allowed' });

  const token = (event.queryStringParameters || {}).token;
  if (!token) return json(400, { error: 'Missing token' });

  try {
    const { data: profile, error: profileError } = await supabase
      .from('member_profiles')
      .select('memberstack_id')
      .eq('calendar_feed_token', token)
      .maybeSingle();

    if (profileError) throw profileError;
    if (!profile) return json(404, { error: 'Invalid or expired calendar link' });

    const memberId = profile.memberstack_id;
    const dtstamp = nowStamp();
    const events = [];

    // ── Deals with a closing date ──
    const { data: closingDeals, error: closingError } = await supabase
      .from('deals')
      .select('id, property_address, closing_date, stage')
      .eq('memberstack_id', memberId)
      .not('closing_date', 'is', null)
      .neq('stage', 'Closed')
      .neq('stage', 'Dead');
    if (closingError) throw closingError;

    for (const deal of closingDeals || []) {
      const address = deal.property_address || 'Untitled property';
      const start = formatDateOnly(deal.closing_date);
      const end = formatDateOnly(addOneDay(deal.closing_date));
      events.push(
        [
          'BEGIN:VEVENT',
          `UID:deal-${deal.id}-closing@forgedbyaris.com`,
          `DTSTAMP:${dtstamp}`,
          `DTSTART;VALUE=DATE:${start}`,
          `DTEND;VALUE=DATE:${end}`,
          `SUMMARY:${icsEscape('Closing: ' + address)}`,
          `DESCRIPTION:${icsEscape('FORGE CRM deal closing — ' + address)}`,
          'END:VEVENT',
        ].join('\r\n')
      );
    }

    // ── Stale deals (same 30-day rule as the CRM's own stale flag) ──
    const { data: allDeals, error: dealsError } = await supabase
      .from('deals')
      .select('id, property_address, stage, updated_at')
      .eq('memberstack_id', memberId)
      .neq('stage', 'Closed')
      .neq('stage', 'Dead');
    if (dealsError) throw dealsError;

    const dealIds = (allDeals || []).map((d) => d.id);
    let latestNoteByDeal = {};
    if (dealIds.length) {
      const { data: notesData, error: notesError } = await supabase
        .from('notes')
        .select('deal_id, created_at')
        .in('deal_id', dealIds)
        .order('created_at', { ascending: false });
      if (!notesError && notesData) {
        for (const n of notesData) {
          if (!latestNoteByDeal[n.deal_id]) latestNoteByDeal[n.deal_id] = n.created_at;
        }
      }
    }

    const now = Date.now();
    const todayStr = new Date().toISOString().slice(0, 10);
    for (const deal of allDeals || []) {
      const lastNote = latestNoteByDeal[deal.id];
      const lastActivityAt = lastNote && new Date(lastNote) > new Date(deal.updated_at) ? lastNote : deal.updated_at;
      const daysSinceActivity = Math.floor((now - new Date(lastActivityAt).getTime()) / (1000 * 60 * 60 * 24));
      const stale = daysSinceActivity >= STALE_DAYS;
      if (!stale) continue;

      const address = deal.property_address || 'Untitled property';
      const start = formatDateOnly(todayStr);
      const end = formatDateOnly(addOneDay(todayStr));
      // Stable UID (no date suffix) — each refresh just moves this same
      // event forward to today for as long as the deal stays stale. Once
      // it's no longer stale, it drops out of the feed and calendar apps
      // remove it on their next sync.
      events.push(
        [
          'BEGIN:VEVENT',
          `UID:deal-${deal.id}-stale@forgedbyaris.com`,
          `DTSTAMP:${dtstamp}`,
          `DTSTART;VALUE=DATE:${start}`,
          `DTEND;VALUE=DATE:${end}`,
          `SUMMARY:${icsEscape('Stale deal — no activity in ' + daysSinceActivity + ' days: ' + address)}`,
          `DESCRIPTION:${icsEscape('FORGE CRM — this deal has had no notes or stage changes in ' + daysSinceActivity + ' days.')}`,
          'END:VEVENT',
        ].join('\r\n')
      );
    }

    // ── Webinars ──
    for (const w of WEBINARS) {
      events.push(
        [
          'BEGIN:VEVENT',
          `UID:${w.uid}@forgedbyaris.com`,
          `DTSTAMP:${dtstamp}`,
          `DTSTART:${w.startUtc}`,
          `DTEND:${w.endUtc}`,
          `SUMMARY:${icsEscape(w.title)}`,
          `DESCRIPTION:${icsEscape('ForgedByAris.com — Where Empires Are Forged')}`,
          'END:VEVENT',
        ].join('\r\n')
      );
    }

    const ics = [
      'BEGIN:VCALENDAR',
      'VERSION:2.0',
      'PRODID:-//FORGE//ARIS Calendar Feed//EN',
      'CALSCALE:GREGORIAN',
      'METHOD:PUBLISH',
      'X-WR-CALNAME:FORGE',
      'X-WR-CALDESC:Deal dates, stale-deal alerts, and webinars from FORGE',
      ...events,
      'END:VCALENDAR',
    ].join('\r\n');

    return {
      statusCode: 200,
      headers: {
        'Content-Type': 'text/calendar; charset=utf-8',
        'Content-Disposition': 'inline; filename="forge-calendar.ics"',
        'Access-Control-Allow-Origin': '*',
      },
      body: ics,
    };
  } catch (err) {
    console.error('calendar-feed error:', err);
    return json(500, { error: 'Server error' });
  }
};
